# Generated by Django 4.1.3 on 2023-01-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumnail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/product_images/thumbnail/'),
        ),
    ]
